/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package ui;


import entity.BloodImage;
import entity.BloodImageCollection; 
import entity.NetworkSetting;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List; 
import javax.imageio.ImageIO;
import javax.swing.JFileChooser; 
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel; 

import util.ExtensionFileFilter;
import util.Util;

 
public class FormPelatihan extends javax.swing.JFrame 
{
    
    List<String> nmfiles;
    JFileChooser flchooser = new JFileChooser();
    Controller con=new Controller();
    /** Creates new form FormEkstraksiCiri */
    public FormPelatihan()
    {
        initComponents();
        Util.TengahWindow(this);
        setResizable(false);
        nmfiles = new ArrayList<String>();
        showFilesImages();
        con.bic = new BloodImageCollection();
    }
    
    private void showFilesImages()
    {
        String[] header = new String[]{"No","Image Path","Pergumpalan Darah"};
        String[][] data = new String[nmfiles.size()][header.length];
        
        for(int i=0;i<nmfiles.size();i++)
        {     
            String ffname = con.bic.getBloodImage(i).getName();
            data[i][0] = String.valueOf(i+1);
            data[i][1] = nmfiles.get(i);
            data[i][2] = ffname;        
        }
        
        jTblGambarDarah.setModel(new DefaultTableModel(data, header));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlue1 = new ui.PanelBlue();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblGambarDarah = new javax.swing.JTable();
        panelYellow3 = new ui.PanelYellow();
        jlblPrewittResult = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtMaxEpoch = new javax.swing.JTextField();
        jTxtErrTolerance = new javax.swing.JTextField();
        jTxtMaxHidden = new javax.swing.JTextField();
        jTxtLearningRate = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblMSE = new javax.swing.JLabel();
        jlblEpoch = new javax.swing.JLabel();
        jbtnStartTraining = new javax.swing.JButton();
        panelYellow6 = new ui.PanelYellow();
        jlblGrayImage = new javax.swing.JLabel();
        panelYellow7 = new ui.PanelYellow();
        jlblOriginalImage = new javax.swing.JLabel();
        panelGreen1 = new ui.PanelGreen();
        btnBrowse = new ui.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();
        jbtnTutup = new ui.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Pelatihan dengan Radial Basis Function dan BackPropagation Neural Network");

        panelBlue1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTblGambarDarah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblGambarDarah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblGambarDarahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblGambarDarah);

        panelBlue1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 960, 220));

        javax.swing.GroupLayout panelYellow3Layout = new javax.swing.GroupLayout(panelYellow3);
        panelYellow3.setLayout(panelYellow3Layout);
        panelYellow3Layout.setHorizontalGroup(
            panelYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPrewittResult, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelYellow3Layout.setVerticalGroup(
            panelYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblPrewittResult, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBlue1.add(panelYellow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter JST"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Max. Epoch");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));

        jLabel8.setText("Learning Rate:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 16, -1, -1));

        jLabel10.setText("Error Tolerance:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, -1));

        jLabel11.setText("Maksimum Hidden:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTxtMaxEpoch.setText("1000");
        jPanel3.add(jTxtMaxEpoch, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 172, -1));

        jTxtErrTolerance.setText("0.001");
        jPanel3.add(jTxtErrTolerance, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 80, 88, -1));

        jTxtMaxHidden.setText("20");
        jPanel3.add(jTxtMaxHidden, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 88, -1));

        jTxtLearningRate.setText("0.1");
        jPanel3.add(jTxtLearningRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 36, 30, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 10, 90));

        jLabel13.setText("Epoch  :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel12.setText("MSE    :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jlblMSE.setText("0.0");
        jPanel3.add(jlblMSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        jlblEpoch.setText("0.0");
        jPanel3.add(jlblEpoch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 130, -1));

        panelBlue1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 370, 210));

        jbtnStartTraining.setText("MULAI LATIH");
        jbtnStartTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartTrainingActionPerformed(evt);
            }
        });
        panelBlue1.add(jbtnStartTraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 260, 110, 30));

        javax.swing.GroupLayout panelYellow6Layout = new javax.swing.GroupLayout(panelYellow6);
        panelYellow6.setLayout(panelYellow6Layout);
        panelYellow6Layout.setHorizontalGroup(
            panelYellow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblGrayImage, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelYellow6Layout.setVerticalGroup(
            panelYellow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblGrayImage, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBlue1.add(panelYellow6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 230));

        javax.swing.GroupLayout panelYellow7Layout = new javax.swing.GroupLayout(panelYellow7);
        panelYellow7.setLayout(panelYellow7Layout);
        panelYellow7Layout.setHorizontalGroup(
            panelYellow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOriginalImage, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelYellow7Layout.setVerticalGroup(
            panelYellow7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYellow7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOriginalImage, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBlue1.add(panelYellow7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setText("Browse..");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pelatihan");

        jbtnTutup.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTutup.setText("Tutup");
        jbtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGreen1Layout = new javax.swing.GroupLayout(panelGreen1);
        panelGreen1.setLayout(panelGreen1Layout);
        panelGreen1Layout.setHorizontalGroup(
            panelGreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGreen1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324)
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGreen1Layout.setVerticalGroup(
            panelGreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGreen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGreen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jbtnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBlue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGreen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jbtnTutupActionPerformed
private int ShowDialogOpenImage()
{    
    FileFilter filter1 = new ExtensionFileFilter("Bitmap and JPEG Files", new String[] { "BMP","JPG"});
    flchooser.setFileFilter(filter1);
    flchooser.setMultiSelectionEnabled(true);
    int tanggapan = flchooser.showOpenDialog(this);   
    return tanggapan;
}
private void addBloodImageFiles(File files[])
{
       BufferedImage img=null;
        try{             
            for(int i=0;i<files.length;i++)
            {
                img = ImageIO.read(files[i]);
                String fname = files[i].getName();
                String arrname[] =fname.split("_");
                String ffname =   arrname[0];               
                con.addBloodImage(img, ffname);
                nmfiles.add(files[i].getAbsolutePath());  
            }
           
        }catch(IOException ex)
        {
            
        }  
}
private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
// TODO add your handling code here:
        int tanggapan = ShowDialogOpenImage(); 
        if(tanggapan==JFileChooser.APPROVE_OPTION)
        {
              addBloodImageFiles(flchooser.getSelectedFiles());
              showFilesImages();

        }
}//GEN-LAST:event_btnBrowseActionPerformed

private void jTblGambarDarahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblGambarDarahMouseClicked
// TODO add your handling code here:
    int baris = jTblGambarDarah.rowAtPoint(evt.getPoint());
    con.viewImageLatih(baris,jlblOriginalImage,jlblGrayImage,jlblPrewittResult);
    
     
    
}//GEN-LAST:event_jTblGambarDarahMouseClicked

  public void appendLog(String text)
{
   // jTxtLog.setText(jTxtLog.getText() + text + "\n");
}

 

public void setStatus(String mse,String epoch)
{
    jlblMSE.setText(mse);
    jlblEpoch.setText(epoch);
}

private void jbtnStartTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartTrainingActionPerformed
// TODO add your handling code here:
    con.setErrTolerance(jTxtErrTolerance.getText());
    con.setMaxHidden(jTxtMaxHidden.getText());
    con.setLearningRate(jTxtLearningRate.getText());
    con.setMaxEpoch(jTxtMaxEpoch.getText());
    con.setfrmTrainANN(this);
    con.pelatihan();
 
}//GEN-LAST:event_jbtnStartTrainingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormPelatihan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnBrowse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTblGambarDarah;
    private javax.swing.JTextField jTxtErrTolerance;
    private javax.swing.JTextField jTxtLearningRate;
    private javax.swing.JTextField jTxtMaxEpoch;
    private javax.swing.JTextField jTxtMaxHidden;
    private javax.swing.JButton jbtnStartTraining;
    private ui.ButtonGlass jbtnTutup;
    private javax.swing.JLabel jlblEpoch;
    private javax.swing.JLabel jlblGrayImage;
    private javax.swing.JLabel jlblMSE;
    private javax.swing.JLabel jlblOriginalImage;
    private javax.swing.JLabel jlblPrewittResult;
    private ui.PanelBlue panelBlue1;
    private ui.PanelGreen panelGreen1;
    private ui.PanelYellow panelYellow3;
    private ui.PanelYellow panelYellow6;
    private ui.PanelYellow panelYellow7;
    // End of variables declaration//GEN-END:variables
}
