/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package ui;

import util.Util;

 
public class FormMenuUtama extends javax.swing.JFrame 
{

    /** Creates new form FormMenuUtama */
    public FormMenuUtama() 
    {
        initComponents();
        Util.TengahWindow(this);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGreen1 = new ui.PanelGreen();
        btnPelatihan = new ui.ButtonGlass();
        jbtnKlasifikasi = new ui.ButtonGlass();
        btnKeluar = new ui.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama Identifikasi Jenis Darah");

        panelGreen1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPelatihan.setForeground(new java.awt.Color(255, 255, 255));
        btnPelatihan.setText("Pelatihan");
        btnPelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelatihanActionPerformed(evt);
            }
        });
        panelGreen1.add(btnPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 23, 155, 94));

        jbtnKlasifikasi.setForeground(new java.awt.Color(255, 255, 255));
        jbtnKlasifikasi.setText("Klasifikasi");
        jbtnKlasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKlasifikasiActionPerformed(evt);
            }
        });
        panelGreen1.add(jbtnKlasifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 147, 155, 98));

        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelGreen1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 280, 150, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGreen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnPelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelatihanActionPerformed
// TODO add your handling code here:
    FormPelatihan frmPelatihan = new  FormPelatihan();
    frmPelatihan.setVisible(true);
}//GEN-LAST:event_btnPelatihanActionPerformed

private void jbtnKlasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKlasifikasiActionPerformed
// TODO add your handling code here:
    FormKlasifikasi formKlasifikasi = new FormKlasifikasi();
    formKlasifikasi.setVisible(true);
            
}//GEN-LAST:event_jbtnKlasifikasiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnKeluar;
    private ui.ButtonGlass btnPelatihan;
    private ui.ButtonGlass jbtnKlasifikasi;
    private ui.PanelGreen panelGreen1;
    // End of variables declaration//GEN-END:variables
}
