/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package ui;

 
import entity.BloodImage;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import pengenalantipedarahjstrbf.BloodClassifier;
import pengenalantipedarahjstrbf.HistogramProjection;
import pengenalantipedarahjstrbf.ImageLoader;
import pengenalantipedarahjstrbf.ImageViewer;
import pengenalantipedarahjstrbf.PreProcessor;
import util.ExtensionFileFilter;

 
public class FormKlasifikasi extends javax.swing.JFrame {
    
    private JFileChooser flchooser = new JFileChooser();
    private List<BloodImage> lstsegmentedImages;
    private String hasil="";    
    private Controller con = new Controller();
     private File[] directories;
     private String selectedTarget="";
    /** Creates new form FormKlasifikasi */
     
    public FormKlasifikasi() 
    {
        initComponents();
        util.Util.TengahWindow(this);
        setResizable(false);
        setTitle("Klasifikasi Jenis Darah");   
        loadFolderBobot();
    }
    
    private void loadFolderBobot()
    {
         directories = new File("bobot/").listFiles(File::isDirectory);
        for(int i=0;i<directories.length;i++)
        {
            jcmbFolderBobot.addItem(directories[i].getName());
        }
    }
    
    private int ShowDialogOpenImage()
    {    
      FileFilter filter1 = new ExtensionFileFilter("Bitmap ,JPEG and PNG Files", new String[] { "BMP","JPG","PNG"});
      flchooser.setFileFilter(filter1);
      flchooser.setMultiSelectionEnabled(true);
      int tanggapan = flchooser.showOpenDialog(this);   
      return tanggapan;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelYellow1 = new ui.PanelYellow();
        btnBrowse = new ui.ButtonGlass();
        jlblGambarUjiBiner = new javax.swing.JLabel();
        jlblCrop3 = new javax.swing.JLabel();
        jlblCrop1 = new javax.swing.JLabel();
        jlblCrop2 = new javax.swing.JLabel();
        jlblGambarUji = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jcmbFolderBobot = new javax.swing.JComboBox<>();
        panelBlue1 = new ui.PanelBlue();
        jlblHasil = new javax.swing.JLabel();
        btnIdentifikasi = new ui.ButtonGlass();
        jlblGolonganDarah = new javax.swing.JLabel();
        jlblAcc = new javax.swing.JLabel();
        btnHitungAkurasi = new ui.ButtonGlass();
        jbtnTutup = new javax.swing.JButton();
        panelGreen1 = new ui.PanelGreen();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelYellow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBrowse.setForeground(new java.awt.Color(-1,true));
        btnBrowse.setText("Browse..");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        panelYellow1.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 10, 190, 40));

        jlblGambarUjiBiner.setForeground(new java.awt.Color(-1,true));
        jlblGambarUjiBiner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGambarUjiBiner.setText(" [ Gambar Tidak Ada]");
        jlblGambarUjiBiner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelYellow1.add(jlblGambarUjiBiner, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 410, 100));

        jlblCrop3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelYellow1.add(jlblCrop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 130, 130));

        jlblCrop1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelYellow1.add(jlblCrop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 130));

        jlblCrop2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelYellow1.add(jlblCrop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 130, 130));

        jlblGambarUji.setForeground(new java.awt.Color(-1,true));
        jlblGambarUji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGambarUji.setText(" [ Gambar Tidak Ada]");
        jlblGambarUji.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelYellow1.add(jlblGambarUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 410, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Location"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelYellow1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 210));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Silahkan Pilih Folder Bobot:");
        panelYellow1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelYellow1.add(jcmbFolderBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, -1));

        getContentPane().add(panelYellow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 660, 440));

        panelBlue1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblHasil.setFont(new java.awt.Font("Dialog", 0, 36));
        jlblHasil.setForeground(new java.awt.Color(-1,true));
        jlblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHasil.setText("????");
        jlblHasil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBlue1.add(jlblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, -1));

        btnIdentifikasi.setForeground(new java.awt.Color(-1,true));
        btnIdentifikasi.setText("Klasifikasi");
        btnIdentifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentifikasiActionPerformed(evt);
            }
        });
        panelBlue1.add(btnIdentifikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 60));

        jlblGolonganDarah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblGolonganDarah.setForeground(new java.awt.Color(255, 255, 0));
        jlblGolonganDarah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGolonganDarah.setText("?");
        jlblGolonganDarah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBlue1.add(jlblGolonganDarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 50));

        jlblAcc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAcc.setForeground(new java.awt.Color(255, 255, 255));
        jlblAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAcc.setText("0 %");
        panelBlue1.add(jlblAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, 30));

        btnHitungAkurasi.setForeground(new java.awt.Color(-1,true));
        btnHitungAkurasi.setText("Hitung Akurasi");
        btnHitungAkurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungAkurasiActionPerformed(evt);
            }
        });
        panelBlue1.add(btnHitungAkurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 60));

        getContentPane().add(panelBlue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 660, 80));

        jbtnTutup.setText("Tutup");
        jbtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 650, 40));

        panelGreen1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24));
        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("KLASIFIKASI JENIS DARAH");
        panelGreen1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 311, 41));

        getContentPane().add(panelGreen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 10, 330, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jbtnTutupActionPerformed

private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
// TODO add your handling code here:
    int tanggapan = ShowDialogOpenImage(); 
    if(tanggapan==JFileChooser.APPROVE_OPTION)
    {
        File[] files=flchooser.getSelectedFiles();
               
            DefaultTableModel tabel = (DefaultTableModel) jTable1.getModel();
            tabel.setRowCount(0);
            for(int i=0;i<files.length;i++)
            {
                //img = ImageIO.read(files[i]);
                Object[] row = {files[i].getName(),files[i].getAbsolutePath()};
                tabel.addRow(row);
            }
           
        
    }
}//GEN-LAST:event_btnBrowseActionPerformed

private void btnIdentifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentifikasiActionPerformed
        
    
        con.pendeteksian(lstsegmentedImages, jlblCrop1, jlblCrop2, jlblCrop3,directories[jcmbFolderBobot.getSelectedIndex()].getName());
        jlblHasil.setText(con.hasil);  
        jlblGolonganDarah.setText(con.GolDarah);
        
}//GEN-LAST:event_btnIdentifikasiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         setSelectedFile(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void setSelectedFile(int idxrow)
    {
        BufferedImage img=null;         
        try
        {
            
            File file=  new File((String) jTable1.getValueAt(idxrow, 1));  
            
            String path = file.getName();          
           String arrname[] =path.split("_");
            selectedTarget = arrname[0];       
            
            img = ImageIO.read(file);
            con.pilihImageUji(img, jlblGambarUji, jlblGambarUjiBiner);
             
        }catch(IOException ex)
        {
            
        }  
    }
    
    private void btnHitungAkurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungAkurasiActionPerformed
        // TODO add your handling code here:
        int icorrect = 0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            System.out.println("Gambar-" + String.valueOf(i+1));
            setSelectedFile(i);
            if (lstsegmentedImages!=null) {
                lstsegmentedImages.clear();
            }
            String result = con.pendeteksian(lstsegmentedImages, jlblCrop1, jlblCrop2, jlblCrop3,directories[jcmbFolderBobot.getSelectedIndex()].getName());
            if (result.equals(selectedTarget))
            {
                icorrect++;
            }
            
        }
        
        double acc = ((double) icorrect)/jTable1.getRowCount();
          String stracc = String.format("%.3f", acc * 100) + " %";
         jlblAcc.setText(stracc);
        
        
    }//GEN-LAST:event_btnHitungAkurasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKlasifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKlasifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKlasifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKlasifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormKlasifikasi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.ButtonGlass btnBrowse;
    private ui.ButtonGlass btnHitungAkurasi;
    private ui.ButtonGlass btnIdentifikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnTutup;
    private javax.swing.JComboBox<String> jcmbFolderBobot;
    private javax.swing.JLabel jlblAcc;
    private javax.swing.JLabel jlblCrop1;
    private javax.swing.JLabel jlblCrop2;
    private javax.swing.JLabel jlblCrop3;
    private javax.swing.JLabel jlblGambarUji;
    private javax.swing.JLabel jlblGambarUjiBiner;
    private javax.swing.JLabel jlblGolonganDarah;
    private javax.swing.JLabel jlblHasil;
    private ui.PanelBlue panelBlue1;
    private ui.PanelGreen panelGreen1;
    private ui.PanelYellow panelYellow1;
    // End of variables declaration//GEN-END:variables
}
